openapi: 3.0.0
info:
  title: Library API v1
  version: 1.0.0
  description: API for managing books and borrows in a library system.
servers:
  - url: http://127.0.0.1:5000/api/v1
    description: Local Development Server
paths:
  /books:
    get:
      summary: Get a list of books with optional pagination and filtering
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: page_size
          schema:
            type: integer
            default: 10
          description: Number of items per page
        - in: query
          name: title
          schema:
            type: string
          description: Filter books by title (case-insensitive, partial match)
        - in: query
          name: author
          schema:
            type: string
          description: Filter books by author (case-insensitive, partial match)
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
                  page:
                    type: integer
                  page_size:
                    type: integer
        '500':
          description: Internal server error
  /users/{id}/borrows:
    get:
      summary: Get borrow records for a specific user
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            required: true
          description: The ID of the user
      responses:
        '200':
          description: A list of borrow records for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Borrow'
                  page:
                    type: integer
                  page_size:
                    type: integer
        '404':
          description: User not found
        '500':
          description: Internal server error
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: The Lord of the Rings
        author:
          type: string
          example: J.R.R. Tolkien
    Borrow:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: The Lord of the Rings
        author:
          type: string
          example: J.R.R. Tolkien
        borrow_date:
          type: string
          format: date
          example: 2023-01-01
        return_date:
          type: string
          format: date
          example: 2023-01-15